from pathlib import Path

BASE_DIR = Path(__file__).parent
DEFAULT_IMAGES_PATH = BASE_DIR / "tests" / "test_images"

FORM_3_5_ASPECT_RATIO = 185 / 55
FORM_4_6_ASPECT_RATIO = 185 / 15

ROI_WIDTH_RATIO = 0.5
ROI_HEIGHT_RATIO = 0.5

DESKEW_MIN_LINE_LENGTH = 100
DESKEW_MAX_LINE_GAP = 10
DESKEW_THRESHOLD = 100

DEFAULT_DEBUG_DIR = Path("debug")
DEBUG_PREPROCESSING_DIR = DEFAULT_DEBUG_DIR / "preprocessing"
DEBUG_LOCALIZATION_DIR = DEFAULT_DEBUG_DIR / "localization"
